---
abstract: 'My Net::LDAP subclass'
author:
  - 'Ben Morrow <ben@morrow.me.uk>'
build_requires:
  Test::More: '0.96'
configure_requires:
  Module::Build: '0.38'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.141520'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: BMORROW-LDAP
provides:
  BMORROW::LDAP:
    file: lib/BMORROW/LDAP.pm
    version: '1'
  BMORROW::LDAP::Entry:
    file: lib/BMORROW/LDAP/Entry.pm
  BMORROW::LDAP::NSS:
    file: lib/BMORROW/LDAP/NSS.pm
  BMORROW::LDAP::Util:
    file: lib/BMORROW/LDAP/Util.pm
requires:
  Net::LDAP: '0'
  Try::Tiny: '0'
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=BMORROW-LDAP
  license: http://opensource.org/licenses/bsd-license.php
  repository: http://github.com/mauzo/BMORROW-LDAP
version: '1'
